#!/usr/bin/env bash
set -e

# Unminify files
cd "$(git rev-parse --show-toplevel)"
FILES="app/files"

gadd() {
	if [ ! -z "$GIT_EDITOR" ]
	then
		echo "git add '$1'"
		git add "$1"
	fi
}

for EXT in js css
do
	while IFS= read -r -d '' FN
	do
		MINIFIED="${FN%-full.$EXT}.$EXT"
		if [ -f "$MINIFIED" ]
		then
			echo "Unminifying $MINIFIED"
			cp "$FN" "$MINIFIED"
			rm "$FN"
		fi
	done < <(find "$FILES" -iname "*.${EXT}" -print0)
done

bin/minify

# gzip SVG files
while IFS= read -r -d '' FN
do
	SVGZ="${FN%.svg}.svgz"
	echo "gzip -9 <'$FN' >'$SVGZ'"
	gzip -9 <"$FN" >"$SVGZ"
done < <(find "$FILES" -iname "*.svg" -print0)

# Update files
gadd "$FILES"

